# This file can be used to pin the rust toolchain to the "stable" version used by shadow CI.
#
# ```sh
# ln -s ci/rust-toolchain-stable.toml rust-toolchain.toml
# ```
#
# See
# https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file
[toolchain]
channel = "1.80.1"
